language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules
    - dist
    - example/build
    - example/node_modules

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn typecheck
        - yarn build

    - stage: release
      if: branch = master AND type = push AND fork = false
      script:
        - yarn run semantic-release
      before_deploy: yarn predeploy
      deploy:
        provider: pages
        github_token: $GH_TOKEN
        local_dir: example/build
        skip_cleanup: true
        keep_history: true
