name: CI Test & Publish
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      # Typescript matchers are broken
      # Check merge of https://github.com/actions/setup-node/pull/125
      - name: Setting up Node.js 12
        uses: Zarel/setup-node@patch-1
        # It's better to set the version strictly to
        # be able to cache node_modules
        with:
          node-version: '12'
      # Caching steps

      # Fetch yarn's directory path, use it in the next step
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # Cache yarn's internal files
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # If that key can be found, just use another cache we have (same prefix)
          restore-keys: |
            ${{ runner.os }}-yarn-
      # Cache every package's node_modules' folder
      - name: node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-optional

      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      # Same as test until Release below
      - name: Checking out repository
        uses: actions/checkout@v2
      # Typescript matchers are broken
      # Check merge of https://github.com/actions/setup-node/pull/125
      - name: Setting up Node.js 12
        uses: Zarel/setup-node@patch-1
        # It's better to set the version strictly to
        # be able to cache node_modules
        with:
          node-version: '12'
      # Caching steps

      # Fetch yarn's directory path, use it in the next step
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # Cache yarn's internal files
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          # If that key can be found, just use another cache we have (same prefix)
          restore-keys: |
            ${{ runner.os }}-yarn-
      # Cache every package's node_modules' folder
      - name: node_modules cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
